# Generated by Django 2.2.18 on 2021-04-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duplicates", "0001_initial_squashed_0003_auto_20180322_1445")
    ]

    operations = [
        migrations.AddField(
            model_name="duplicatesuggestion",
            name="rejection_reasoning",
            field=models.CharField(
                blank=True,
                help_text="Reason for rejecting duplicate suggestion",
                max_length=255,
            ),
        )
    ]
