# Generated by Django 3.2.10 on 2021-12-14 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("people", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("duplicates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="duplicatesuggestion",
            name="other_person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duplicate_suggestion_other_person",
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="duplicatesuggestion",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="duplicate_suggestion",
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="duplicatesuggestion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="duplicatesuggestion",
            unique_together={("person", "other_person")},
        ),
    ]
