# Generated by Django 2.2.18 on 2021-04-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("duplicates", "0002_add_reasoning_field")]

    operations = [
        migrations.AlterField(
            model_name="duplicatesuggestion",
            name="rejection_reasoning",
            field=models.TextField(
                blank=True,
                help_text="Reason for rejecting duplicate suggestion",
            ),
        )
    ]
