# Generated by Django 4.2.16 on 2025-07-21 14:03

import model_utils.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("duplicates", "0003_reasoning_as_textfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duplicatesuggestion",
            name="status",
            field=model_utils.fields.StatusField(
                choices=[
                    ("suggested", "Suggested"),
                    ("not_duplicate", "Not duplicate"),
                ],
                default="suggested",
                max_length=100,
                no_check_for_status=True,
                verbose_name="status",
            ),
        ),
    ]
