# Generated by Django 5.2.15 on 2026-08-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duplicates", "0005_remove_duplicatesuggestion_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="duplicatesuggestion",
            name="suggestion_reason",
            field=models.TextField(
                blank=True, help_text="Reason for suggesting duplicates"
            ),
        ),
    ]
