repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.2.2'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix, --extend-exclude, TCH]
    - id: ruff-format
