sudo: false

notifications:
  email: false

language: python
python:
  - '3.5'
  - '3.6'
addons:
  postgresql: "9.5"
  apt:
    packages:
    - rabbitmq-server

before_install:
  - sudo apt-get update && sudo apt install -y python3-tk ghostscript

install:
  - pip install tox coveralls tox-travis
  # Make sure pip is at the latest version:
  - pip install -U pip
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then pip install black ; fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then black -l 80 --check . ; fi
  - tox -e travis
after_success:
  - coveralls
