# Generated by Django 3.2.10 on 2021-12-14 17:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import parties.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Party",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "ec_id",
                    models.CharField(
                        db_index=True,
                        help_text="\n            An ID issued by The Electoral Commission in their party register,\n            with the exception of Democracy Club psuedo IDs for special parties\n        ",
                        max_length=20,
                        unique=True,
                        verbose_name="Electoral Commission Idenfitier",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Party name"),
                ),
                (
                    "register",
                    models.CharField(
                        db_index=True,
                        help_text="\n            Normally either `GB` or `NI` depending on the\n            country the party is registered in. Pseudo-parties don't have a\n            register, so this field is nullable.\n        ",
                        max_length=2,
                        null=True,
                        verbose_name="Party register",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Registered", "Registered"),
                            ("Deregistered", "Deregistered"),
                        ],
                        db_index=True,
                        max_length=255,
                        verbose_name="Party registration status",
                    ),
                ),
                ("date_registered", models.DateField()),
                ("date_deregistered", models.DateField(null=True)),
                (
                    "legacy_slug",
                    models.CharField(
                        blank=True,
                        help_text="\n            DEPRECATED: A slug used in URLs that comes from a previous way of modelling parties.\n            This field will be removed in the future in favour of the `ec_id`.\n            ",
                        max_length=256,
                        unique=True,
                    ),
                ),
                (
                    "current_candidates",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("total_candidates", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="PartyEmblem",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "ec_emblem_id",
                    models.PositiveIntegerField(
                        primary_key=True, serialize=False
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=parties.models.emblem_upload_path
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("date_approved", models.DateField(null=True)),
                ("default", models.BooleanField(default=False)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emblems",
                        to="parties.party",
                    ),
                ),
            ],
            options={"ordering": ("-default", "ec_emblem_id")},
        ),
        migrations.CreateModel(
            name="PartyDescription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("description", models.CharField(max_length=800)),
                ("date_description_approved", models.DateField(null=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="parties.party",
                    ),
                ),
            ],
            options={"get_latest_by": "modified", "abstract": False},
        ),
    ]
