# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-03 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("parties", "0002_add_independent_party")]

    operations = [
        migrations.AlterModelOptions(
            name="party", options={"ordering": ("name",)}
        )
    ]
