# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-03 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("parties", "0003_party_ordering")]

    operations = [
        migrations.AddField(
            model_name="party",
            name="legacy_slug",
            field=models.CharField(blank=True, max_length=256, unique=False),
        )
    ]
