# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-03 18:33
from __future__ import unicode_literals

from django.db import migrations
from parties.importer import make_slug


def add_legacy_slug(apps, schema_editor):
    Party = apps.get_model("parties", "Party")
    for party in Party.objects.all():
        party.legacy_slug = make_slug(party.ec_id)
        party.save()
    ind = Party.objects.get(ec_id="ynmp-party:2")
    ind.legacy_slug = "ynmp-party:2"
    ind.save()


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0004_party_legacy_slug"),
        ("popolo", "0015_move_organization_to_parties"),
    ]

    operations = [
        migrations.RunPython(add_legacy_slug, migrations.RunPython.noop)
    ]
