# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-03 12:14
from __future__ import unicode_literals

from django.db import migrations


def add_speaker(apps, schema_editor):
    Party = apps.get_model("parties", "Party")
    Party.objects.update_or_create(
        ec_id="ynmp-party:12522",
        legacy_slug="ynmp-party:12522",
        defaults={
            "name": "Speaker seeking re-election",
            "date_registered": "1376-04-28",
        },
    )


class Migration(migrations.Migration):
    dependencies = [("parties", "0006_legacy_slug_unique")]

    operations = [migrations.RunPython(add_speaker, migrations.RunPython.noop)]
