# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-06 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("parties", "0007_add_speaker")]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="ec_id",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        )
    ]
