# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("parties", "0009_slug_help_text")]

    operations = [
        migrations.AddField(
            model_name="party",
            name="current_candidates",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="party",
            name="total_candidates",
            field=models.IntegerField(default=0),
        ),
    ]
