# Generated by Django 2.2.4 on 2019-10-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("parties", "0011_add_initial_candidates_counts")]

    operations = [
        migrations.AlterField(
            model_name="party",
            name="current_candidates",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="party",
            name="ec_id",
            field=models.CharField(
                db_index=True,
                help_text="\n            An ID issued by The Electoral Commission in their party register,\n            with the exception of Democracy Club psuedo IDs for special parties\n        ",
                max_length=20,
                unique=True,
                verbose_name="Electoral Commission Idenfitier",
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="legacy_slug",
            field=models.CharField(
                blank=True,
                help_text="\n            DEPRECATED: A slug used in URLs that comes from a previous way of modelling parties.\n            This field will be removed in the future in favour of the `ec_id`.\n            ",
                max_length=256,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Party name"),
        ),
        migrations.AlterField(
            model_name="party",
            name="register",
            field=models.CharField(
                db_index=True,
                help_text="\n            Normally either `GB` or `NI` depending on the\n            country the party is registered in. Pseudo-parties don't have a\n            register, so this field is nullable.\n        ",
                max_length=2,
                null=True,
                verbose_name="Party register",
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="status",
            field=models.CharField(
                choices=[
                    ("Registered", "Registered"),
                    ("Deregistered", "Deregistered"),
                ],
                db_index=True,
                max_length=255,
                verbose_name="Party registration status",
            ),
        ),
        migrations.AlterField(
            model_name="party",
            name="total_candidates",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="partyemblem",
            name="ec_emblem_id",
            field=models.PositiveIntegerField(
                primary_key=True, serialize=False
            ),
        ),
    ]
