# Generated by Django 2.2.18 on 2021-04-06 07:47

from django.db import migrations


def add_independent_party_descriptions(apps, schema_editor):
    Party = apps.get_model("parties", "Party")
    party = Party.objects.get(ec_id="ynmp-party:2")
    for i, desc in enumerate(["[blank]", "[No party listed]"]):
        party.descriptions.update_or_create(description=desc)


class Migration(migrations.Migration):

    dependencies = [("parties", "0012_add_party_docs")]

    operations = [
        migrations.RunPython(
            add_independent_party_descriptions, migrations.RunPython.noop
        )
    ]
