# Generated by Django 3.2.4 on 2021-09-28 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("parties", "0013_add_independent_descriptions")]

    operations = [
        migrations.AlterModelOptions(
            name="partydescription", options={"get_latest_by": "modified"}
        )
    ]
