# Generated by Django 3.2.10 on 2022-01-19 15:24

from django.db import migrations
from django.db.models import Value
from django.db.models.functions import Replace


def replace_dash_with_hyphen(apps, schema_editor):

    Party = apps.get_model("parties", "Party")
    PartyDescription = apps.get_model("parties", "PartyDescription")
    Party.objects.update(name=Replace("name", Value("\u2013"), Value("\u002d")))
    PartyDescription.objects.update(
        description=Replace("description", Value("\u2013"), Value("\u002d"))
    )


class Migration(migrations.Migration):

    dependencies = [("parties", "0014_alter_partydescription_options")]

    operations = [
        migrations.RunPython(
            code=replace_dash_with_hyphen,
            reverse_code=migrations.RunPython.noop,
        )
    ]
