# Generated by Django 3.2.10 on 2022-01-19 11:37

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [("parties", "0015_replace_dash_with_hyphen")]

    operations = [CreateExtension(name="fuzzystrmatch")]
