# Generated by Django 3.2.10 on 2022-01-19 11:37

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("parties", "0015_replace_dash_with_hyphen")]

    operations = [CreateExtension(name="fuzzystrmatch")]
