# Generated by Django 4.1.7 on 2023-05-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parties", "0017_alter_party_ec_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="alternative_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
