# Generated by Django 4.1.3 on 2022-12-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0018_partyspending"),
    ]

    operations = [
        migrations.AddField(
            model_name="partyspending",
            name="published",
            field=models.DateField(null=True),
        ),
    ]
