# Generated by Django 4.1.7 on 2023-05-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0018_party_alternative_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="ec_data",
            field=models.JSONField(default=dict),
        ),
    ]
