# Generated by Django 4.1.7 on 2023-05-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parties", "0019_party_ec_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partyemblem",
            options={"ordering": ("-default", "-active", "ec_emblem_id")},
        ),
        migrations.AddField(
            model_name="partyemblem",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
