# Generated by Django 4.1.7 on 2023-05-31 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0020_alter_partyemblem_options_partyemblem_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partydescription",
            options={"ordering": ["-active"]},
        ),
        migrations.AddField(
            model_name="partydescription",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
