# Generated by Django 4.1.7 on 2023-07-12 16:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0021_alter_partydescription_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="party",
            name="nations",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=3),
                help_text='\n                Some subset of ["ENG", "WAL", "SCO"],\n                depending on where the party fields candidates. \n                Nullable as not applicable to NI-based parties.\n            ',
                max_length=3,
                null=True,
                size=None,
                verbose_name="Party nations",
            ),
        ),
    ]
