# Generated by Django 5.2.8 on 2026-02-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parties", "0023_alter_partyemblem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partyemblem",
            name="description",
            field=models.TextField(),
        ),
    ]
