# Generated by Django 5.2.12 on 2026-03-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parties", "0024_alter_partyemblem_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="partydescription",
            name="pseudo_description",
            field=models.BooleanField(default=False),
        ),
    ]
