# Generated by Django 5.2.12 on 2026-04-01 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parties", "0025_partydescription_pseudo_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="party",
            options={"ordering": ("name",), "verbose_name_plural": "parties"},
        ),
    ]
