# Generated by Django 3.2.10 on 2021-12-14 17:21

from django.db import migrations, models
import django.db.models.deletion
import facebook_data.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("people", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="FacebookAdvert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad_id",
                    models.CharField(
                        help_text="The Facebook ID for this advert",
                        max_length=500,
                    ),
                ),
                (
                    "ad_json",
                    models.JSONField(
                        help_text="The JSON returned from the Facebook Graph API for this advert"
                    ),
                ),
                (
                    "associated_url",
                    models.CharField(
                        blank=True,
                        help_text="The URL used to import the data – useful for being able to remove incorrect advertsfor a person without re-importing every advert for them",
                        max_length=800,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="A screenshot of the rendered advert",
                        max_length=512,
                        upload_to=facebook_data.models.advert_image_path,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.person",
                    ),
                ),
            ],
            options={
                "ordering": ("-ad_json__ad_delivery_start_time",),
                "get_latest_by": "ad_json__ad_delivery_start_time",
            },
        )
    ]
