# Generated by Django 2.2.4 on 2019-09-15 16:04

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("people", "0017_set_vandalism_list")]

    operations = [
        migrations.CreateModel(
            name="FacebookAdvert",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_id", models.CharField(max_length=500)),
                ("ad_json", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="people.Person",
                    ),
                ),
                (
                    "associated_url",
                    models.CharField(
                        blank=True,
                        help_text="The URL used to import the data – useful for being able to remove incorrect advertsfor a person without re-importing every advert for them",
                        max_length=800,
                    ),
                ),
            ],
        )
    ]
