# Generated by Django 2.2.4 on 2019-12-08 14:05

from django.db import migrations, models
import facebook_data.models


class Migration(migrations.Migration):

    dependencies = [("facebook_data", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="facebookadvert",
            name="image",
            field=models.ImageField(
                blank=True,
                max_length=512,
                upload_to=facebook_data.models.advert_image_path,
            ),
        )
    ]
