# Generated by Django 2.2.16 on 2021-04-01 07:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import facebook_data.models


class Migration(migrations.Migration):

    dependencies = [("facebook_data", "0002_facebookadvert_image")]

    operations = [
        migrations.AlterModelOptions(
            name="facebookadvert",
            options={
                "get_latest_by": "ad_json__ad_delivery_start_time",
                "ordering": ("-ad_json__ad_delivery_start_time",),
            },
        ),
        migrations.AlterField(
            model_name="facebookadvert",
            name="ad_id",
            field=models.CharField(
                help_text="The Facebook ID for this advert", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="facebookadvert",
            name="ad_json",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                help_text="The JSON returned from the Facebook Graph API for this advert"
            ),
        ),
        migrations.AlterField(
            model_name="facebookadvert",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="A screenshot of the rendered advert",
                max_length=512,
                upload_to=facebook_data.models.advert_image_path,
            ),
        ),
    ]
