# Generated by Django 3.2.10 on 2021-12-14 17:21

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Election",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "ee_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Stores the modified timestamp from EE",
                        null=True,
                    ),
                ),
                ("slug", models.CharField(max_length=128, unique=True)),
                ("for_post_role", models.CharField(max_length=128)),
                (
                    "winner_membership_role",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("candidate_membership_role", models.CharField(max_length=128)),
                ("election_date", models.DateField(db_index=True)),
                ("name", models.CharField(max_length=128)),
                ("current", models.BooleanField()),
                (
                    "use_for_candidate_suggestions",
                    models.BooleanField(default=False),
                ),
                ("party_lists_in_use", models.BooleanField(default=False)),
                (
                    "people_elected_per_post",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="The number of people who are elected per post in this election. 0 means a variable number of winners",
                    ),
                ),
                (
                    "default_party_list_members_to_show",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("show_official_documents", models.BooleanField(default=False)),
                ("ocd_division", models.CharField(blank=True, max_length=250)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "modgov_url",
                    models.URLField(
                        blank=True,
                        help_text="Used to store a possible ModGov url that can be used to scrape information for this election",
                        null=True,
                    ),
                ),
            ],
            options={"get_latest_by": "modified", "abstract": False},
        )
    ]
