# Generated by Django 3.2.10 on 2021-12-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("popolo", "0001_initial"), ("elections", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="election",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="popolo.organization",
            ),
        )
    ]
