# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("elections", "0014_cleanup_for_post_role")]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="election_date",
            field=models.DateField(db_index=True),
        )
    ]
