# Generated by Django 2.2.4 on 2019-10-29 17:04

from django.db import migrations, models


def set_people_elected_per_post_to_zero(apps, schema_editor):
    Election = apps.get_model("elections", "Election")
    Election.objects.filter(people_elected_per_post__lt=0).update(
        people_elected_per_post=0
    )


class Migration(migrations.Migration):
    dependencies = [("elections", "0015_election_date_index")]

    operations = [
        migrations.RunPython(
            set_people_elected_per_post_to_zero, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="election",
            name="default_party_list_members_to_show",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="election",
            name="people_elected_per_post",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="The number of people who are elected per post in this election. 0 means a variable number of winners",
            ),
        ),
    ]
