# Generated by Django 3.2.4 on 2021-09-29 16:10

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("elections", "0017_election_modgov_url")]

    operations = [
        migrations.AlterModelOptions(
            name="election", options={"get_latest_by": "modified"}
        ),
        migrations.AddField(
            model_name="election",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="election",
            name="ee_modified",
            field=models.DateTimeField(
                blank=True,
                help_text="Stores the modified timestamp from EE",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="election",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
