# Generated by Django 3.2.4 on 2021-09-29 16:12

from django.db import migrations

from elections.helpers import four_weeks_before_election_date


def add_created_date(apps, schema_editor):
    Election = apps.get_model("elections", "Election")
    for election in Election.objects.iterator():
        election.created = four_weeks_before_election_date(election=election)
        election.save()


class Migration(migrations.Migration):

    dependencies = [("elections", "0018_add_timestamps_to_election")]

    operations = [
        migrations.RunPython(
            code=migrations.RunPython.noop,
            reverse_code=migrations.RunPython.noop,
        )
    ]
