# Generated by Django 3.2.4 on 2021-10-20 10:26

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("elections", "0019_add_created")]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, db_index=True, verbose_name="modified"
            ),
        )
    ]
