# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("official_documents", "0023_remove_election_and_post")]

    operations = [
        migrations.AlterModelOptions(
            name="officialdocument", options={"get_latest_by": "modified"}
        ),
        migrations.AddField(
            model_name="officialdocument",
            name="relevant_pages",
            field=models.CharField(
                max_length=50,
                null=True,
                verbose_name="The pages containing information about this ballot",
            ),
        ),
    ]
