# Generated by Django 2.2.18 on 2021-04-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("official_documents", "0025_rename_post_election_fk_to_ballot")
    ]

    operations = [
        migrations.AlterField(
            model_name="officialdocument",
            name="relevant_pages",
            field=models.CharField(
                max_length=256,
                null=True,
                verbose_name="The pages containing information about this ballot",
            ),
        )
    ]
