# Generated by Django 4.2.6 on 2023-12-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("official_documents", "0029_textractresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="textractresult",
            name="analysis_status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("SUCCEEDED", "Succeeded"),
                    ("IN_PROGRESS", "In Progress"),
                    ("FAILED", "Failed"),
                    ("PARTIAL_SUCCESS", "Partial Success"),
                ],
                default="NOT_STARTED",
            ),
        ),
    ]
