# Generated by Django 4.2.8 on 2024-03-05 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("official_documents", "0030_textractresult_analysis_status"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TextractResult",
        ),
    ]
