# Generated by Django 4.2.10 on 2024-03-25 17:06

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
import official_documents.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0020_alter_election_modified"),
        ("official_documents", "0031_delete_textractresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionSOPN",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(
                        max_length=1200,
                        upload_to=official_documents.models.election_sopn_file_name,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="The URL of this document", max_length=1200
                    ),
                ),
                (
                    "election",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elections.election",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
            },
        ),
    ]
