# Generated by Django 4.2.10 on 2024-03-25 18:55

import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
import official_documents.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "candidates",
            "0085_alter_personredirect_options_personredirect_created_and_more",
        ),
        ("official_documents", "0032_electionsopn"),
    ]

    operations = [
        migrations.CreateModel(
            name="BallotSOPNHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(
                        max_length=1200,
                        upload_to=official_documents.models.ballot_sopn_file_name,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="The URL of this document", max_length=1200
                    ),
                ),
                (
                    "ballot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sopn_history",
                        to="candidates.ballot",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BallotSOPN",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "uploaded_file",
                    models.FileField(
                        max_length=1200,
                        upload_to=official_documents.models.ballot_sopn_file_name,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        help_text="The URL of this document", max_length=1200
                    ),
                ),
                (
                    "ballot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sopn",
                        to="candidates.ballot",
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
