# Generated by Django 4.2.10 on 2024-03-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("official_documents", "0033_ballotsopnhistory_ballotsopn"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballotsopn",
            name="relevant_pages",
            field=models.CharField(
                default="all",
                help_text="The pages in the ElectionSOPN that relate to this Ballot",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ballotsopnhistory",
            name="relevant_pages",
            field=models.CharField(
                default="all",
                help_text="The pages in the ElectionSOPN that relate to this Ballot",
                max_length=20,
            ),
        ),
    ]
