# Generated by Django 4.2.10 on 2024-03-26 14:26
from django.db import migrations

"""
This was a data backfill migration
It used to do something
but now it is just a no-op
"""


class Migration(migrations.Migration):
    dependencies = [
        ("official_documents", "0034_ballotsopn_relevant_pages_and_more"),
        (
            "sopn_parsing",
            "0009_alter_awstextractparsedsopn_official_document_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop, migrations.RunPython.noop
        )
    ]
