# Generated by Django 4.2.10 on 2024-04-02 19:58

import django.core.validators
import official_documents.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("official_documents", "0036_electionsopn_page_matching_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballotsopn",
            name="uploaded_file",
            field=models.FileField(
                max_length=1200,
                upload_to=official_documents.models.ballot_sopn_file_name,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpeg", "jpg", "png"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ballotsopnhistory",
            name="uploaded_file",
            field=models.FileField(
                max_length=1200,
                upload_to=official_documents.models.ballot_sopn_file_name,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "jpeg", "jpg", "png"]
                    )
                ],
            ),
        ),
    ]
