# Generated by Django 4.2.11 on 2024-06-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("official_documents", "0037_alter_ballotsopn_uploaded_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballotsopn",
            name="replacement_reason",
            field=models.CharField(
                blank=True,
                help_text="Please be as descriptive as possible to explain why the replacement SOPN is needed",
                max_length=255,
                verbose_name="Reason for replacement",
            ),
        ),
        migrations.AddField(
            model_name="ballotsopnhistory",
            name="replacement_reason",
            field=models.CharField(
                blank=True,
                help_text="Please be as descriptive as possible to explain why the replacement SOPN is needed",
                max_length=255,
                verbose_name="Reason for replacement",
            ),
        ),
        migrations.AddField(
            model_name="electionsopn",
            name="replacement_reason",
            field=models.CharField(
                blank=True,
                help_text="Please be as descriptive as possible to explain why the replacement SOPN is needed",
                max_length=255,
                verbose_name="Reason for replacement",
            ),
        ),
    ]
