# Generated by Django 5.2.12 on 2026-03-12 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elections", "0020_alter_election_modified"),
        ("official_documents", "0038_ballotsopn_replacement_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electionsopn",
            name="election",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="elections.election",
            ),
        ),
    ]
