# Generated by Django 4.2.16 on 2025-04-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("official_documents", "0038_ballotsopn_replacement_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballotsopn",
            name="withdrawal_detected",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ballotsopnhistory",
            name="withdrawal_detected",
            field=models.BooleanField(default=False),
        ),
    ]
