# Generated by Django 5.2.12 on 2026-03-16 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("official_documents", "0039_alter_electionsopn_election"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballotsopn",
            name="election_sopn",
            field=models.ForeignKey(
                blank=True,
                help_text="If this BallotSOPN was created by splitting an ElectionSOPN, the ElectionSOPN from whence it came",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="official_documents.electionsopn",
            ),
        ),
        migrations.AddField(
            model_name="ballotsopnhistory",
            name="election_sopn",
            field=models.ForeignKey(
                blank=True,
                help_text="If this BallotSOPN was created by splitting an ElectionSOPN, the ElectionSOPN from whence it came",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="official_documents.electionsopn",
            ),
        ),
    ]
