# Generated by Django 5.2.12 on 2026-03-18 09:16

from django.db import migrations
from django.db.models import Count, F


def backfill_election_sopn_id(apps, schema_editor):
    BallotSOPN = apps.get_model("official_documents", "BallotSOPN")
    ballot_sopns = (
        BallotSOPN.objects.using(schema_editor.connection.alias)
        .all()
        .filter(
            election_sopn_id__isnull=True,
            ballot__election__electionsopn__isnull=False,
            source_url=F("ballot__election__electionsopn__source_url"),
        )
        .exclude(relevant_pages="all")
        .annotate(electionsopn_count=Count("ballot__election__electionsopn"))
        .filter(electionsopn_count=1)
        .select_related("ballot__election")
        .prefetch_related("ballot__election__electionsopn_set")
        .order_by("ballot__ballot_paper_id")
    )

    for ballot_sopn in ballot_sopns:
        ballot_sopn.election_sopn = (
            ballot_sopn.ballot.election.electionsopn_set.all().first()
        )
        ballot_sopn.save()


def delete_election_sopn_id(apps, schema_editor):
    BallotSOPN = apps.get_model("official_documents", "BallotSOPN")
    BallotSOPN.objects.using(schema_editor.connection.alias).update(
        election_sopn=None
    )


class Migration(migrations.Migration):
    dependencies = [
        ("official_documents", "0040_ballotsopn_election_sopn_and_more"),
    ]

    operations = [
        migrations.RunPython(
            backfill_election_sopn_id, reverse_code=delete_election_sopn_id
        )
    ]
