# Generated by Django 5.2.12 on 2026-03-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("official_documents", "0041_backfill_election_sopn_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="electionsopn",
            name="blank_pages",
            field=models.JSONField(default=list),
        ),
    ]
