---
- name: restart nginx
  service: name=nginx state=restarted
  become: true
  become_user: root

- name: reload nginx
  service: name=nginx state=reloaded
  become: true
  become_user: root

- name: restart web frontend
  systemd:
    state: restarted
    daemon_reload: yes
    name: "{{ project_name }}_gunicorn"
  become: true
  become_user: root

- name: reload systemd
  become: true
  become_user: root
  command: systemctl daemon-reload

- name: restart rsyslog
  service: name=rsyslog state=restarted
  become: true
  become_user: root
