# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-28 13:26
from __future__ import unicode_literals

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteBanner",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Markdown formatted text to show on every page"
                    ),
                ),
                ("published", models.BooleanField(default=False)),
                ("show_until", models.DateTimeField()),
            ],
            options={"abstract": False},
        )
    ]
