orbs:
  aws-sg-white-list-circleci-ip: inokappa/aws-sg-white-list-circleci-ip@0.0.3
  aws-cli: circleci/aws-cli@4.1.3
  slack: circleci/slack@4.13.3
version: 2.1

jobs:
  build_and_test:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: cimg/python:3.8.15
        environment:
          CIRCLECI: true
          PGHOST: 127.0.0.1
          RUN_ENV: test
      - image: cimg/postgres:12.15
        environment:
          POSTGRES_USER: ynr
          POSTGRES_DB: ynr
      - image: cimg/redis:6.2.6


      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
           keys:
             - v6-dependencies-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/sopn_parsing.txt" }}-{{ checksum "requirements/testing.txt" }}
      - run:
          name: Install APT packages
          command: |
            sudo rm -rf /var/lib/apt/lists/*
            sudo apt-get update
            sudo apt-get install python-tk ghostscript
      - run:
          name: Install pandoc
          command: |
            wget https://github.com/jgm/pandoc/releases/download/2.17.1.1/pandoc-2.17.1.1-1-amd64.deb
            sudo dpkg -i pandoc-2.17.1.1-1-amd64.deb
            sudo apt install texlive-latex-base texlive-latex-extra
      - run:
          name: Create venv
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install -U pip
      - run:
          name: Install Coveralls
          command: |
            . .venv/bin/activate
            pip install coveralls
      - run:
          name: install dependencies
          command: |
            . .venv/bin/activate
            pip install -r requirements/testing.txt

      - save_cache:
          paths:
            - .venv
          key: v6-dependencies-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/sopn_parsing.txt" }}-{{ checksum "requirements/testing.txt" }}

      - run:
          name: Pre test checks
          environment:
            CIRCLECI: true
            RUN_ENV: test
          command: |
            . .venv/bin/activate
            pip check
            ruff .
            ruff format .
            python manage.py check
            python manage.py makemigrations --check
      - run:
          name: run tests
          environment:
            CIRCLECI: true
            RUN_ENV: test
          command: |
            . .venv/bin/activate
            pytest -x --cov-report= --cov --junitxml=test-results/junit.xml

      # Coverage
      - run:
          name: Update Coveralls
          command: |
            . .venv/bin/activate
            coveralls

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

  db_migrate:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Run any outstanding migrations
          command: |
            ./scripts/ci/dbmigrate.sh
  deploy:
    docker:
      - image: cimg/python:3.8.15
        environment:
          CIRCLECI: true
          PGHOST: 127.0.0.1
          RUN_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - aws-cli/setup
      - restore_cache:
          keys:
            - v1-deploy-{{ checksum "requirements/deploy.txt" }}
      - run:
          name: Create venv
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install -U pip
      - run:
          name: install dependencies
          command: |
            . .venv/bin/activate
            pip install -r requirements/deploy.txt
      - aws-sg-white-list-circleci-ip/add:
          group-id: sg-807bc0e9
          port: 22
      - run:
          name: Ansible Deploy
          command: |
            . .venv/bin/activate
            cd deploy
            ansible-playbook deploy.yml -e branch=$CIRCLE_SHA1
      - aws-sg-white-list-circleci-ip/del:
          group-id: sg-807bc0e9
          port: 22
      - save_cache:
          paths:
            - .venv
          key: v1-deploy-{{ checksum "requirements/deploy.txt" }}
                        
      - slack/notify:
          event: fail
          template: basic_fail_1

  static_tests:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.8.15-node
    steps:
      - checkout
      - run:
          name: Create venv and install Python and Node dependencies
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install -r requirements/testing.txt
            npm install --save=false .
      - run:
          name: Pre test checks
          environment:
            CIRCLECI: true
            RUN_ENV: test
          command: |
            . .venv/bin/activate
            pip check
            ruff .
            ruff format .
            python manage.py check
            python manage.py makemigrations --check

  container_test_build_and_push:
    working_directory: ~/repo
    docker:
      - image: cimg/base:current
      - image: cimg/postgres:16.4
        name: dbpsql
        environment:
          POSTGRES_USER: ynr
          POSTGRES_DB: ynr
    steps:
      - checkout
      - aws-cli/setup
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build container images
          command: |
            ./scripts/container.image.build.bash prod
            ./scripts/container.image.build.bash test
      - run:
          name: Check that compose is happy
          command: |
            docker compose version
            docker compose config
            # No-op, due to a shared layer cache with earlier image builds.
            docker compose build
      - run:
          name: Run app tests
          command: |
            net="$(docker network inspect $(docker network ls -q -f "label=task-network") --format '{{.Name}}')"
            docker run -it --rm \
              --net="$net" \
              -e PGHOST=dbpsql \
              -e CIRCLECI=true \
              \
              ynr:test \
              pytest -x --ignore=node_modules
      - run:
          name: Tag and push the image
          command: |
              TAG="${CIRCLE_SHA1:0:7}"
              echo Using the tag ${TAG}
              docker tag ynr:prod public.ecr.aws/h3q9h5r7/dc-test/ynr:${TAG}
              aws ecr-public get-login-password --profile default --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/h3q9h5r7/dc-test/ynr
              docker push public.ecr.aws/h3q9h5r7/dc-test/ynr:${TAG}

  service_update:
    working_directory: ~/repo
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Update the task definition to the newly pushed image
          command: |
              IMAGE_TAG="${CIRCLE_SHA1:0:7}"
              ./scripts/ci/update-ecs-task.sh $IMAGE_TAG
      - run:
          name: Wait for the service to stabilise
          command: ./scripts/ci/wait-for-stable-ecs-service.sh

  cdk_test_and_deploy:
    docker:
      - image: cimg/python:3.8.15-node
    working_directory: ~/repo/
    steps:
      - checkout
      - run:
          name: Create CDK venv and install Python and Node dependencies
          command: |
            python -m venv ./cdk/venv
            . ./cdk/venv/bin/activate
            pip install -r requirements/cdk.txt
            npm install --save=false .
      - run:
          name: Check that CDK stacks synthesise
          command: |
            . ./cdk/venv/bin/activate
            npx cdk synth
      - run:
          name: Run CDK tests
          command: |
            . ./cdk/venv/bin/activate
            pytest ./cdk
      - run:
          name: Show would-be changes in the stack
          command: |
            . ./cdk/venv/bin/activate
            npx cdk diff
      - when:
          condition:
            equal: [ "ci/test", << pipeline.git.branch >> ]
          steps:
            - run:
                name: Deploy CDK stack infra
                command: |
                  . ./cdk/venv/bin/activate
                  npx cdk deploy --verbose --require-approval never --progress events

workflows:
  test_build_deploy:
    jobs:
    - build_and_test
    - deploy:
        requires:
        - build_and_test
        filters: { branches: { only: [ main, master, deployment-upgrades] } }
        context: [ deployment-production-ynr, slack-secrets ]
  container:
    jobs:
      ##########
      # All envs
      ##########
      - static_tests:
          context: [ deployment-ecs-development-ynr ]

      #############
      # Development
      #############
      - cdk_test_and_deploy:
          context: [ deployment-ecs-development-ynr ]
          requires:
            - static_tests
          filters: { branches: { only: [ "ci/test"] } }
      - container_test_build_and_push:
          requires:
            - cdk_test_and_deploy
          context: [ deployment-ecs-development-ynr ]
          filters: { branches: { only: [ "ci/test"] } }
      - service_update:
          requires:
            - container_test_build_and_push
          context: [ deployment-ecs-development-ynr ]
          filters: { branches: { only: [ "ci/test"] } }
      - db_migrate:
          requires:
            - service_update
          context: [ deployment-ecs-development-ynr ]
          filters: { branches: { only: [ "ci/test"] } }
