orbs:
  aws-sg-white-list-circleci-ip: inokappa/aws-sg-white-list-circleci-ip@0.0.3
  aws-cli: circleci/aws-cli@4.1.3
  slack: circleci/slack@4.13.3
version: 2.1

jobs:
  post_deploy_checks:
    docker:
      - image: cimg/base:current
    parameters:
        dc-environment:
          type: enum
          enum: [ development, staging, production ]
    environment:
      DC_ENVIRONMENT: "<<parameters.dc-environment>>"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
         name: Run hurl tests
         command: |
            sudo apt-add-repository -y ppa:lepapareil/hurl
            sudo apt install -y jq hurl
            cd hurl-tests
            hurl --test -m 10 --variable host=$(jq -r '.YnrStack|to_entries|map(select(.key|startswith("YnrServiceServiceURL"))|.value)[0]' ../ynr-${DC_ENVIRONMENT}-stack-out.json) *.hurl

  build_and_test:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: cimg/python:3.8.15
        environment:
          CIRCLECI: true
          PGHOST: 127.0.0.1
          RUN_ENV: test
      - image: cimg/postgres:12.15
        environment:
          POSTGRES_USER: ynr
          POSTGRES_DB: ynr
      - image: cimg/redis:6.2.6


      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
           keys:
             - v6-dependencies-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/sopn_parsing.txt" }}-{{ checksum "requirements/testing.txt" }}
      - run:
          name: Install APT packages
          command: |
            sudo rm -rf /var/lib/apt/lists/*
            sudo apt-get update
            sudo apt-get install python-tk ghostscript
      - run:
          name: Install pandoc
          command: |
            wget https://github.com/jgm/pandoc/releases/download/2.17.1.1/pandoc-2.17.1.1-1-amd64.deb
            sudo dpkg -i pandoc-2.17.1.1-1-amd64.deb
            sudo apt install texlive-latex-base texlive-latex-extra
      - run:
          name: Create venv
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install -U pip
      - run:
          name: Install Coveralls
          command: |
            . .venv/bin/activate
            pip install coveralls
      - run:
          name: install dependencies
          command: |
            . .venv/bin/activate
            pip install -r requirements/testing.txt

      - save_cache:
          paths:
            - .venv
          key: v6-dependencies-{{ checksum "requirements/base.txt" }}-{{ checksum "requirements/sopn_parsing.txt" }}-{{ checksum "requirements/testing.txt" }}

      - run:
          name: Pre test checks
          environment:
            CIRCLECI: true
            RUN_ENV: test
          command: |
            . .venv/bin/activate
            pip check
            ruff .
            ruff format . --check
            DJANGO_SECRET_KEY=fake python manage.py check
            DJANGO_SECRET_KEY=fake python manage.py makemigrations --check
      - run:
          name: run tests
          environment:
            CIRCLECI: true
            RUN_ENV: test
          command: |
            . .venv/bin/activate
            pytest -x --cov-report= --cov --junitxml=test-results/junit.xml

      # Coverage
      - run:
          name: Update Coveralls
          command: |
            . .venv/bin/activate
            coveralls

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

  db_migrate:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Run any outstanding migrations
          command: |
            ./scripts/ci/dbmigrate.sh

  deploy:
    docker:
      - image: cimg/python:3.8.15
        environment:
          CIRCLECI: true
          PGHOST: 127.0.0.1
          RUN_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - aws-cli/setup
      - restore_cache:
          keys:
            - v1-deploy-{{ checksum "requirements/deploy.txt" }}
      - run:
          name: Create venv
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install -U pip
      - run:
          name: install dependencies
          command: |
            . .venv/bin/activate
            pip install -r requirements/deploy.txt
      - aws-sg-white-list-circleci-ip/add:
          group-id: sg-807bc0e9
          port: 22
      - run:
          name: Ansible Deploy
          command: |
            . .venv/bin/activate
            cd deploy
            ansible-playbook deploy.yml -e branch=$CIRCLE_SHA1
      - aws-sg-white-list-circleci-ip/del:
          group-id: sg-807bc0e9
          port: 22
      - save_cache:
          paths:
            - .venv
          key: v1-deploy-{{ checksum "requirements/deploy.txt" }}
                        
      - slack/notify:
          event: fail
          template: basic_fail_1

  static_tests:
    working_directory: ~/repo
    docker:
      - image: cimg/python:3.8.15-node
    steps:
      - checkout
      - run:
          name: Create venv and install Python and Node dependencies
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install -r requirements/testing.txt
            npm install --save=false .
      - run:
          name: Pre test checks
          environment:
            CIRCLECI: true
            RUN_ENV: test
          command: |
            . .venv/bin/activate
            pip check
            ruff .
            ruff format . --check
            DJANGO_SECRET_KEY=fake python manage.py check
            DJANGO_SECRET_KEY=fake python manage.py makemigrations --check
      - run:
          name: Run shellcheck
          command: |
            sudo apt install -y shellcheck
            find scripts/ -type f \( -name *.sh -o -name *.bash \) -print0 | xargs -r0 shellcheck

  container_build_and_test:
    working_directory: ~/repo
    docker:
      - image: cimg/base:current
      - image: cimg/postgres:16.4
        name: dbpsql
        environment:
          POSTGRES_USER: ynr
          POSTGRES_DB: ynr
    steps:
      - checkout
      - aws-cli/setup
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build container images
          command: |
            ./scripts/container.image.build.bash prod
            ./scripts/container.image.build.bash test
      - run:
          name: Check that compose is happy
          command: |
            docker compose version
            docker compose config
            # No-op, due to a shared layer cache with earlier image builds.
            docker compose build
      - run:
          name: Run app tests
          command: |
            net="$(docker network inspect $(docker network ls -q -f "label=task-network") --format '{{.Name}}')"
            docker run -it --rm \
              --net="$net" \
              -e PGHOST=dbpsql \
              -e CIRCLECI=true \
              \
              ynr:test \
              pytest -x --ignore=node_modules

      - when:
          condition:
            or:
              - equal: [ "ci/test", << pipeline.git.branch >> ]
              - equal: [ "staging", << pipeline.git.branch >> ]
              - equal: [ "master", << pipeline.git.branch >> ]
          steps:
            - run:
                name: Save the image for later so we can tag it for the env and subsequently deploy it
                command: |
                  mkdir -p images
                  docker image save -o "images/dc-ynr-${CIRCLE_SHA1}" ynr:prod

            - persist_to_workspace:
                root: .
                paths:
                  - images

  deploy_cdk_environment:
    docker:
      - image: cimg/python:3.8.15-node
    working_directory: ~/repo/
    parameters:
        dc-environment:
          type: enum
          enum: [ development, staging, production ]
    environment:
      DC_ENVIRONMENT: "<<parameters.dc-environment>>"
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Create CDK venv and install Python and Node dependencies
          command: |
            python -m venv ./cdk/venv
            . ./cdk/venv/bin/activate
            pip install -r requirements/cdk.txt
            npm install --save=false .
      - run:
          name: Bootstrap the CDK environment
          command: |
            . ./cdk/venv/bin/activate
            npx cdk bootstrap
      - run:
          name: Show would-be changes in the stack
          command: |
            . ./cdk/venv/bin/activate
            npx cdk diff

      - run:
          name: Deploy CDK stack infra
          command: |
            . ./cdk/venv/bin/activate
            npx cdk deploy --verbose --require-approval never --progress events --outputs-file ynr-<<parameters.dc-environment>>-stack-out.json
      # Because we use stable image tags we need to force a redeploy of the
      # service when the container is updated
      - run:
          name: Force deploy the service to pick up the new image
          command: |
              IMAGE_TAG="${CIRCLE_SHA1:0:7}"
              ./scripts/ci/update-ecs-task.sh $IMAGE_TAG
      - run:
          name: Wait for the service to stabilise
          command: ./scripts/ci/wait-for-stable-ecs-service.sh

      - persist_to_workspace:
          root: .
          paths:
            - ynr-<<parameters.dc-environment>>-stack-out.json

  container_push_and_tag:
    docker:
      - image: cimg/python:3.8.15-node
    working_directory: ~/repo/
    parameters:
        dc-environment:
          type: enum
          enum: [ development, staging, production ]
    environment:
      DC_ENVIRONMENT: "<<parameters.dc-environment>>"
    steps:
      #- checkout
      - aws-cli/setup
      - setup_remote_docker:
          docker_layer_caching: true

      - attach_workspace:
          at: .

      - run:
          name: Load the previously saved image
          command: |
            docker image load < "images/dc-ynr-${CIRCLE_SHA1}"

      - run:
          name: Validate the saved image
          command: |
            docker image ls

      - run:
          name: Push the image with a stable tag for the environment
          command: |
              docker tag ynr:prod public.ecr.aws/h3q9h5r7/dc-test/ynr:<< parameters.dc-environment>>
              aws ecr-public get-login-password --profile default --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/h3q9h5r7/dc-test/ynr
              docker push public.ecr.aws/h3q9h5r7/dc-test/ynr:<< parameters.dc-environment>>

      - run:
          name: Push the image with a content-deterministic tag
          command: |
              docker inspect --format="{{index .RepoDigests 0}}" public.ecr.aws/h3q9h5r7/dc-test/ynr:<< parameters.dc-environment>> | cut -d: -f 2 | tee manifest-tag
              TAG=$(cat manifest-tag)
              echo Using the tag ${TAG}
              docker tag ynr:prod public.ecr.aws/h3q9h5r7/dc-test/ynr:${TAG}
              docker push public.ecr.aws/h3q9h5r7/dc-test/ynr:${TAG}

  cdk_test:
    docker:
      - image: cimg/python:3.8.15-node
    working_directory: ~/repo/
    parameters:
        dc-environment:
          type: enum
          enum: [ development, staging, production ]
    environment:
      DC_ENVIRONMENT: "<<parameters.dc-environment>>"
    steps:
      - checkout
      - run:
          name: Create CDK venv and install Python and Node dependencies
          command: |
            python -m venv ./cdk/venv
            . ./cdk/venv/bin/activate
            pip install -r requirements/cdk.txt
            npm install --save=false .
      - run:
          name: Check that CDK stacks synthesise
          command: |
            . ./cdk/venv/bin/activate
            npx cdk synth
      - run:
          name: Run CDK tests
          command: |
            . ./cdk/venv/bin/activate
            pytest ./cdk


workflows:
  test_build_deploy:
    jobs:
    - build_and_test
    - deploy:
        requires:
        - build_and_test
        filters: { branches: { only: [ main, master] } }
        context: [ deployment-production-ynr, slack-secrets ]
  container:
    jobs:
      ##########
      # All envs
      ##########
      - static_tests:
          context: [ deployment-ecs-development-ynr ]
      - cdk_test:
          context: [ deployment-ecs-development-ynr ]
          dc-environment: development
      - container_build_and_test

      #############
      # Development
      #############
      - container_push_and_tag:
          name: "DEV push container"
          requires:
            - static_tests
            - container_build_and_test
          context: [ deployment-ecs-development-ynr ]
          filters: { branches: { only: [ "ci/test"] } }
          dc-environment: development
      - deploy_cdk_environment:
          name: DEV cdk deploy
          context: [ deployment-ecs-development-ynr ]
          requires:
            - cdk_test
            - DEV push container
          filters: { branches: { only: [ "ci/test"] } }
          dc-environment: development
      - db_migrate:
          name: DEV db migrate
          requires:
            - DEV cdk deploy
          context: [ deployment-ecs-development-ynr ]
          filters: { branches: { only: [ "ci/test"] } }
      - post_deploy_checks:
          name: DEV post deploy checks
          requires:
            - DEV db migrate
          dc-environment: development
          filters: { branches: { only: [ "ci/test"] } }

      #########
      # Staging
      #########
      - container_push_and_tag:
          name: "STAGING push container"
          requires:
            - static_tests
            - container_build_and_test
          # One might expect to see the staging context here, but the
          # development one is required because that's the account where the
          # AWS ECR registry is found
          context: [ deployment-ecs-development-ynr ]
          filters: { branches: { only: [ "staging" ] } }
          dc-environment: staging
      - deploy_cdk_environment:
          name: STAGING cdk deploy
          context: [ deployment-ecs-staging-ynr ]
          requires:
            - cdk_test
            - STAGING push container
          filters: { branches: { only: [ "staging" ] } }
          dc-environment: staging
      - db_migrate:
          name: STAGING db migrate
          requires:
            - STAGING cdk deploy
          context: [ deployment-ecs-staging-ynr ]
          filters: { branches: { only: [ "staging" ] } }
      - post_deploy_checks:
          name: STAGING post deploy checks
          requires:
            - STAGING db migrate
          dc-environment: staging
          filters: { branches: { only: [ "staging" ] } }

      ############
      # Production
      ############
      - container_push_and_tag:
          name: "PRODUCTION push container"
          requires:
            - static_tests
            - container_build_and_test
          # One might expect to see the prod context here, but the
          # development one is required because that's the account where the
          # AWS ECR registry is found
          context: [ deployment-ecs-development-ynr ]
          filters: { branches: { only: [ "master" ] } }
          dc-environment: production
      - deploy_cdk_environment:
          name: PRODUCTION cdk deploy
          context: [ deployment-ecs-production-ynr ]
          requires:
            - cdk_test
            - PRODUCTION push container
          filters: { branches: { only: [ "master" ] } }
          dc-environment: production
      - db_migrate:
          name: PRODUCTION db migrate
          requires:
            - PRODUCTION cdk deploy
          context: [ deployment-ecs-production-ynr ]
          filters: { branches: { only: [ "master" ] } }
      - post_deploy_checks:
          name: PRODUCTION post deploy checks
          requires:
            - PRODUCTION db migrate
          dc-environment: production
          filters: { branches: { only: [ "master" ] } }
