# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-24 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("people", "0006_move_person_gfks")]

    operations = [
        migrations.RemoveField(model_name="person", name="end_date"),
        migrations.RemoveField(model_name="person", name="start_date"),
    ]
