# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-02 11:40
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0010_copy_email_to_person_identifier")]

    operations = [
        migrations.AlterModelOptions(
            name="personidentifier",
            options={"ordering": ("value_type", "-modified")},
        ),
        migrations.AlterField(
            model_name="personidentifier",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tmp_person_identifiers",
                to="people.Person",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="personidentifier",
            unique_together={
                ("person", "internal_identifier", "value_type"),
                ("person", "value"),
                ("person", "value_type"),
            },
        ),
    ]
