# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("people", "0011_set_tmp_unique_constraints")]

    operations = [
        migrations.AddField(
            model_name="person",
            name="favourite_biscuit",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Favourite biscuit 🍪"
            ),
        )
    ]
