# Generated by Django 2.2.4 on 2019-08-22 09:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0014_remove_person_email")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="birth_date",
            field=models.CharField(
                blank=True,
                help_text="A date of birth",
                max_length=20,
                verbose_name="birth date",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="death_date",
            field=models.CharField(
                blank=True,
                help_text="A date of death",
                max_length=20,
                verbose_name="death date",
            ),
        ),
    ]
