# Generated by Django 2.2.4 on 2019-09-09 19:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0015_date_lengths")]

    operations = [
        migrations.AddField(
            model_name="person",
            name="edit_limitations",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NO_STATUS", ""),
                    ("LIABLE_TO_VANDALISM", "Liable to vandalism"),
                    ("EDITS_PREVENTED", "Edits prevented"),
                ],
                max_length=100,
            ),
        )
    ]
