# Generated by Django 2.2.16 on 2021-01-06 19:03
import json

from django.db import migrations


def populate_json_versions(apps, schema):
    Person = apps.get_model("people", "Person")
    for person in Person.objects.all():
        try:
            person.json_versions = json.loads(person.versions)
        except json.decoder.JSONDecodeError as e:
            person.json_versions = {}
        person.save()


class Migration(migrations.Migration):

    dependencies = [("people", "0020_add_json_versions")]

    operations = [
        migrations.RunPython(populate_json_versions, migrations.RunPython.noop)
    ]
