# Generated by Django 2.2.16 on 2021-01-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("people", "0021_populate_json_versions")]

    operations = [
        migrations.RemoveField(model_name="person", name="versions"),
        migrations.RenameField(
            model_name="person", old_name="json_versions", new_name="versions"
        ),
    ]
