# Generated by Django 2.2.16 on 2021-03-13 08:51

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("people", "0022_rename_json_versions_field")]

    operations = [
        migrations.AddField(
            model_name="person",
            name="name_search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        )
    ]
