# Generated by Django 2.2.16 on 2021-03-13 15:19

import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("people", "0023_add_search_vector_field")]

    operations = [
        migrations.AddIndex(
            model_name="person",
            index=django.contrib.postgres.indexes.GistIndex(
                fields=["name_search_vector"], name="name_vector_search_index"
            ),
        )
    ]
