# Generated by Django 2.2.16 on 2021-04-01 07:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0026_add_person_name_synonym")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="edit_limitations",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NEEDS_REVIEW", "Needs review"),
                    ("EDITS_PREVENTED", "Edits prevented"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="personidentifier",
            name="extra_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                help_text="For storing any additional data against this field.\n                     Used by bots, not humans.",
                null=True,
            ),
        ),
    ]
