# Generated by Django 2.2.16 on 2021-03-31 11:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("people", "0026_add_person_name_synonym")]

    operations = [
        migrations.AlterField(
            model_name="personidentifier",
            name="extra_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict,
                help_text="For storing any additional data against this field.\n                     Used by bots, not humans.",
            ),
        )
    ]
