# Generated by Django 2.2.18 on 2021-04-06 12:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("people", "0027_auto_20210401_0811")]

    operations = [
        migrations.AlterField(
            model_name="personidentifier",
            name="extra_data",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict,
                help_text="For storing any additional data against this field.\n                     Used by bots, not humans.",
            ),
        )
    ]
