# Generated by Django 2.2.18 on 2021-04-23 13:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("people", "0028_add_default_to_extra_data")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="versions",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        )
    ]
