# Generated by Django 2.2.20 on 2021-06-16 15:59

from django.db import migrations


def copy_created_at(apps, schema_editor):
    Person = apps.get_model("people", "Person")
    for person in Person.objects.iterator():
        person.created = person.created_at
        person.save()


def copy_created(apps, schema_editor):
    Person = apps.get_model("people", "Person")
    for person in Person.objects.iterator():
        person.created_at = person.created
        person.save()


class Migration(migrations.Migration):

    dependencies = [("people", "0030_auto_20210616_1642")]

    operations = [
        migrations.RunPython(code=copy_created_at, reverse_code=copy_created)
    ]
