# Generated by Django 2.2.20 on 2021-06-16 16:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("people", "0031_copy_created")]

    operations = [
        migrations.RemoveField(model_name="person", name="created_at"),
        migrations.RemoveField(model_name="person", name="updated_at"),
    ]
