# Generated by Django 3.2.4 on 2021-09-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("people", "0032_auto_20210616_1700")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="versions",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="personidentifier",
            name="extra_data",
            field=models.JSONField(
                default=dict,
                help_text="For storing any additional data against this field.\n                     Used by bots, not humans.",
            ),
        ),
    ]
