# Generated by Django 3.2.4 on 2022-02-15 10:51

from django.db import migrations
from django.db.models import Count, Q


def delete_non_primary_images(apps, schema_editor):
    PersonImage = apps.get_model("people", "PersonImage")
    PersonImage.objects.filter(is_primary=False).delete()

    # a few People in the database have more than one primary image that need
    # to be cleaned up manually
    Person = apps.get_model("people", "Person")
    people = Person.objects.annotate(
        primary_images=Count("images", filter=Q(images__is_primary=True))
    ).filter(primary_images__gt=1)
    for person in people:
        # when multiple primary images existed, the first image was considered
        # the primary image
        primary = person.images.first().pk
        person.images.exclude(pk=primary).delete()


class Migration(migrations.Migration):

    dependencies = [("people", "0035_alter_person_birth_date")]

    operations = [
        migrations.RunPython(
            code=delete_non_primary_images,
            reverse_code=migrations.RunPython.noop,
        )
    ]
