# Generated by Django 3.2.4 on 2022-02-15 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("people", "0036_delete_non_primary_images")]

    operations = [
        migrations.AlterField(
            model_name="personimage",
            name="person",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="image",
                to="people.person",
            ),
        )
    ]
