# Generated by Django 4.1.7 on 2023-09-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0041_add_person_name_edit_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="delisted",
            field=models.BooleanField(
                default=False,
                help_text="Mark this person as de-listed in search engines. Might take some days to come in to effect",
            ),
        ),
    ]
