# Generated by Django 4.2.3 on 2023-10-03 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0042_person_delisted"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="biography_last_updated",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="biography last updated"
            ),
        ),
    ]
