# Generated by Django 4.2.11 on 2024-05-25 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0045_mark_uncontested_people_elected"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="personidentifier",
            unique_together={
                ("person", "value_type"),
                ("person", "internal_identifier", "value_type"),
            },
        ),
    ]
