# Generated by Django 5.2.8 on 2025-11-26 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "people",
            "0047_alter_personimage_options_personimage_created_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="biography_last_updated",
        ),
    ]
