# Generated by Django 3.2.10 on 2021-12-15 10:54

from django.db import migrations, models
import django.db.migrations.operations.special


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# cached_counts.migrations.0003_set_default_election
# cached_counts.migrations.0004_constituency_to_post


def set_uk_2015_election(apps, schema_editor):
    CachedCount = apps.get_model("cached_counts", "CachedCount")
    for cc in CachedCount.objects.all():
        if not cc.election:
            cc.election = "2015"
            cc.save()


def change_constituency_to_post(apps, schema_editor):
    CachedCount = apps.get_model("cached_counts", "CachedCount")
    for cc in CachedCount.objects.all():
        if cc.count_type == "constituency":
            cc.count_type = "post"
            cc.save()


class Migration(migrations.Migration):

    replaces = [
        ("cached_counts", "0001_initial"),
        ("cached_counts", "0002_cachedcount_election"),
        ("cached_counts", "0003_set_default_election"),
        ("cached_counts", "0004_constituency_to_post"),
        ("cached_counts", "0005_delete_cachedcount"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CachedCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count_type", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("count", models.IntegerField()),
                ("object_id", models.CharField(blank=True, max_length=100)),
                (
                    "election",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
            ],
            options={"ordering": ["-count", "name"]},
        ),
        migrations.RunPython(
            code=set_uk_2015_election,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.RunPython(code=change_constituency_to_post),
        migrations.DeleteModel(name="CachedCount"),
    ]
