# Generated by Django 4.2.10 on 2024-04-10 08:18

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cached_counts", "0005_delete_cachedcount"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionReport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "election_type",
                    models.CharField(
                        choices=[
                            ("parl", "parl"),
                            ("nia", "nia"),
                            ("senedd", "senedd"),
                            ("sp", "sp"),
                            ("gla", "gla"),
                            ("local", "local"),
                            ("pcc", "pcc"),
                            ("mayor", "mayor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("election_date", models.DateField()),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "unique_together": {("election_type", "election_date")},
            },
        ),
    ]
