# Generated by Django 3.2 on 2022-04-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cached_counts", "0006_cachedreport")]

    operations = [
        migrations.AddField(
            model_name="cachedreport",
            name="group_id",
            field=models.CharField(blank=True, max_length=300),
        )
    ]
