# Generated by Django 4.2.6 on 2024-02-26 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ynr_refactoring", "0003_move_person_identifiers"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PageNotFoundLog",
        ),
    ]
