# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-18 10:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import popolo.behaviors.models



class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0044_remove_membership_fk_to_election'),
        ('popolo', '0002_update_models_from_upstream'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='elected',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='membership',
            name='party_list_position',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='post_election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.PostExtraElection'),
        ),
    ]
