# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-18 10:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import popolo.behaviors.models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0004_move-extra-data-to-base'),
    ]
operations = [
    migrations.AlterField(
        model_name='membership',
        name='post_election',
        field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.PostExtraElection'),
    ),
 ]
