# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-14 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0007_python_3_migrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='versions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='not_standing',
            field=models.ManyToManyField(related_name='persons_not_standing_tmp',
                                         to='elections.Election'),
        ),
    ]
