# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-14 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("popolo", "0008_add_person_extra_fields")]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop, migrations.RunPython.noop
        )
    ]
