# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-17 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0046_delete_person_extra"),
        ("popolo", "0009_move_extra_person_data_to_base"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="not_standing",
            field=models.ManyToManyField(
                related_name="persons_not_standing", to="elections.Election"
            ),
        )
    ]
