# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-21 20:44
from __future__ import unicode_literals

from django.db import migrations


def add_extra_fields_to_base(apps, schema_editor):
    Post = apps.get_model("popolo", "Post")

    # First, delete any Post objects with no extra
    Post.objects.filter(extra=None).delete()

    for base in Post.objects.all().select_related("extra"):
        base.slug = base.extra.slug
        base.group = base.extra.group
        base.party_set = base.extra.party_set
        base.save()


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0048_move_pee_postextra_to_post"),
        ("popolo", "0011_add_post_extra_fields"),
    ]

    operations = [
        migrations.RunPython(
            add_extra_fields_to_base, migrations.RunPython.noop
        )
    ]
