# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-21 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("popolo", "0012_move_post_extra_data_to_base")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="elections",
            field=models.ManyToManyField(
                related_name="posts",
                through="candidates.PostExtraElection",
                to="elections.Election",
            ),
        ),
    ]
