# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-03 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("popolo", "0015_move_organization_to_parties")]

    operations = [
        migrations.RemoveField(model_name="membership", name="organization")
    ]
