# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-03 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("popolo", "0016_remove_membership_organization")]

    operations = [
        migrations.RemoveField(model_name="membership", name="on_behalf_of")
    ]
