# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-18 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("popolo", "0018_protect_membership_on_party_deletion")]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="register",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="organization",
            name="slug",
            field=models.CharField(blank=True, max_length=256, unique=False),
        ),
    ]
