# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-18 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("popolo", "0019_move_organization_extra_fields_to_base")]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop, migrations.RunPython.noop
        )
    ]
