# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-18 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("popolo", "0020_move_extra_organization_data_to_base")]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="slug",
            field=models.CharField(blank=True, max_length=256, unique=True),
        )
    ]
