# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-20 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("popolo", "0021_auto_20180918_1534"),
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop, migrations.RunPython.noop
        )
    ]
