# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-26 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("popolo", "0022_populate_person_image_from_image")]

    operations = [
        migrations.RemoveField(model_name="area", name="content_type"),
        migrations.RemoveField(model_name="area", name="parent"),
        migrations.AlterUniqueTogether(
            name="areai18name", unique_together=set()
        ),
        migrations.RemoveField(model_name="areai18name", name="area"),
        migrations.RemoveField(model_name="areai18name", name="language"),
        migrations.RemoveField(model_name="membership", name="area"),
        migrations.RemoveField(model_name="organization", name="area"),
        migrations.RemoveField(model_name="post", name="area"),
        migrations.DeleteModel(name="Area"),
        migrations.DeleteModel(name="AreaI18Name"),
    ]
