# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-23 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("popolo", "0024_remove_person_image"),
        ("people", "0004_move_person_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="person",
            field=models.ForeignKey(
                help_text="The person who is a party to the relationship",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="people.Person",
            ),
        )
    ]
