# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-22 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("popolo", "0026_remove_stale_models")]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={
                "ordering": (
                    "party__name",
                    "party_list_position",
                    "person__name",
                )
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name="post", unique_together={("slug", "organization")}
        ),
    ]
