# Generated by Django 2.2.4 on 2019-10-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("popolo", "0028_rename_post_election_to_ballot")]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="party_list_position",
            field=models.PositiveSmallIntegerField(null=True),
        )
    ]
