# Generated by Django 2.2.4 on 2019-11-04 20:53

from django.db import migrations
from django.db.models import Count


def deduplicate_other_names(apps, schema_editor):
    OtherName = apps.get_model("popolo", "OtherName")

    people_with_duplicate_names = (
        OtherName.objects.all()
        .values("name", "object_id")
        .annotate(count=Count("object_id"))
        .filter(count__gt=1)
    )

    for dupe_name_person in people_with_duplicate_names:
        other_names_for_person = OtherName.objects.filter(
            object_id=dupe_name_person["object_id"],
            name=dupe_name_person["name"],
        )
        for other_name in other_names_for_person[1:]:
            other_name.delete()


class Migration(migrations.Migration):
    dependencies = [("popolo", "0029_positive_int_field")]

    operations = [
        migrations.RunPython(deduplicate_other_names, migrations.RunPython.noop)
    ]
