# Generated by Django 2.2.4 on 2019-11-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("popolo", "0030_remove_duplicate_other_names"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="othername",
            unique_together={("name", "object_id", "content_type")},
        )
    ]
