# Generated by Django 2.2.4 on 2020-01-16 22:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("popolo", "0032_add_post_identifiers")]

    operations = [
        migrations.AlterUniqueTogether(
            name="post",
            unique_together={("slug", "organization", "start_date")},
        )
    ]
