# Generated by Django 2.2.16 on 2021-03-10 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("parties", "0012_add_party_docs"),
        ("popolo", "0035_attach_memberships_to_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="party_description",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parties.PartyDescription",
                help_text="The party description for this membership",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="party_description_text",
            field=models.CharField(
                blank=True,
                max_length=800,
                help_text="The text of the party description at the time of this membership. This is useful if the associated party description subsequently changed",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="party_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                help_text="The name of the associated party at the time of this membership. This is useful if the associated party subsequently changed name",
            ),
        ),
    ]
