# Generated by Django 2.2.20 on 2021-06-16 16:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("popolo", "0040_copy_created")]

    operations = [
        migrations.RemoveField(model_name="contactdetail", name="created_at"),
        migrations.RemoveField(model_name="contactdetail", name="updated_at"),
        migrations.RemoveField(model_name="membership", name="created_at"),
        migrations.RemoveField(model_name="membership", name="updated_at"),
        migrations.RemoveField(model_name="organization", name="created_at"),
        migrations.RemoveField(model_name="organization", name="updated_at"),
        migrations.RemoveField(model_name="post", name="created_at"),
        migrations.RemoveField(model_name="post", name="updated_at"),
    ]
