# Generated by Django 3.2.4 on 2021-09-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("popolo", "0042_auto_20210929_1710")]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="elected",
            field=models.BooleanField(null=True),
        )
    ]
