# Generated by Django 3.2.4 on 2021-12-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("popolo", "0045_clean_up_blank_party_names")]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="party_name",
            field=models.CharField(
                help_text="The name of the associated party at the time of this membership. This is useful if the associated party subsequently changed name",
                max_length=255,
            ),
        )
    ]
