# Generated by Django 3.2.12 on 2022-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parties", "0017_alter_party_ec_id"),
        ("popolo", "0046_remove_blank_from_party_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="previous_party_affiliations",
            field=models.ManyToManyField(
                blank=True,
                related_name="alliated_memberships",
                to="parties.Party",
            ),
        )
    ]
