# Generated by Django 4.1.7 on 2023-03-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("popolo", "0047_membership_previous_party_affiliations"),
    ]

    operations = [
        migrations.AddField(
            model_name="othername",
            name="needs_review",
            field=models.BooleanField(default=False),
        ),
    ]
