# Generated by Django 4.2.3 on 2023-09-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popolo", "0048_othername_needs_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="deselected",
            field=models.BooleanField(
                default=False,
                help_text="Whether this candidate was deselected by their party, but remains on the ballot",
            ),
        ),
    ]
