# Generated by Django 4.2.3 on 2023-09-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popolo", "0049_membership_deselected"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="deselected_source",
            field=models.URLField(
                blank=True,
                help_text="A URL to a source document about the deselection",
            ),
        ),
    ]
