# Generated by Django 4.2.3 on 2023-10-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popolo", "0050_membership_deselected_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="deselected",
            field=models.BooleanField(
                default=False,
                help_text="Whether this candidate was deselected by their party, but remains on the ballot",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="deselected_source",
            field=models.URLField(
                blank=True,
                help_text="A URL to a source document about the deselection",
                null=True,
            ),
        ),
    ]
