# Generated by Django 4.2.16 on 2025-07-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popolo", "0052_fix_territory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="territory_code",
            field=models.CharField(
                choices=[
                    ("ENG", "England"),
                    ("NIR", "Northern Ireland"),
                    ("SCT", "Scotland"),
                    ("WLS", "Wales"),
                ],
                help_text="\n        The territory within Great Britain that this post is in.\n        One of SCT, WLS, ENG, NIR\n        ",
                max_length=10,
            ),
        ),
    ]
