# Generated by Django 5.2.8 on 2026-01-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popolo", "0053_alter_post_territory_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="sopn_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The person's name, exactly as it is printed on the SOPN",
                max_length=255,
            ),
        ),
    ]
