# Generated by Django 5.2.8 on 2026-02-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("popolo", "0053_alter_post_territory_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="sopn_first_names",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The person's first names, exactly as they are printed on the SOPN",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="sopn_last_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The person's last name, exactly as it is printed on the SOPN",
                max_length=255,
            ),
        ),
    ]
