---
- hosts: worker
  vars_files:
    - vars.yml
  gather_facts: true
  become: true
  become_user: "{{ project_name }}"
  remote_user: ubuntu
  roles:
    - common
  tasks:
    - name: Import SOPNs from Google Sheet
      django_manage:
        command: "candidates_import_statements_of_persons_nominated {{ item.url }}"
        app_path: "{{ project_root }}/code"
        virtualenv: "{{ project_root }}/env"
      with_items:
        - { name: "2023 Locals", "url": "https://docs.google.com/spreadsheets/d/e/2PACX-1vS-S4lA6qKxeFbxL-e7DM9WeFEBzaqQvQbfeM4GWNln55C4gANfOVTL0bsWKhwm_iV-_MIUulTGhdUI/pub?gid=916854898&single=true&output=csv" }
        - { name: "2023 NI", "url": "https://docs.google.com/spreadsheets/d/e/2PACX-1vS-S4lA6qKxeFbxL-e7DM9WeFEBzaqQvQbfeM4GWNln55C4gANfOVTL0bsWKhwm_iV-_MIUulTGhdUI/pub?gid=752865614&single=true&output=csv" }
