# Generated by Django 4.2.6 on 2023-11-14 13:22

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("official_documents", "0029_textractresult"),
        ("sopn_parsing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AWSTextractParsedSOPN",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("raw_data", models.TextField()),
                (
                    "raw_data_type",
                    models.CharField(default="pandas", max_length=255),
                ),
                ("parsed_data", models.TextField(null=True)),
                (
                    "status",
                    models.CharField(default="unparsed", max_length=255),
                ),
                (
                    "sopn",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="official_documents.officialdocument",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
