# Generated by Django 4.2.8 on 2024-03-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sopn_parsing", "0003_rename_parsedsopn_camelotparsedsopn"),
        ("sopn_parsing", "0003_rename_parsedsopn_camelotparsedsopn"),
    ]

    operations = [
        migrations.AddField(
            model_name="awstextractparsedsopn",
            name="job_id",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="awstextractparsedsopn",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("SUCCEEDED", "Succeeded"),
                    ("IN_PROGRESS", "In Progress"),
                    ("FAILED", "Failed"),
                    ("PARTIAL_SUCCESS", "Partial Success"),
                ],
                default="NOT_STARTED",
                max_length=255,
            ),
        ),
    ]
