# Generated by Django 4.2.10 on 2024-03-26 14:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sopn_parsing", "0005_awstextractparsedsopnimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="awstextractparsedsopn",
            old_name="sopn",
            new_name="official_document",
        ),
        migrations.RenameField(
            model_name="camelotparsedsopn",
            old_name="sopn",
            new_name="official_document",
        ),
    ]
