# Generated by Django 4.2.10 on 2024-03-25 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("official_documents", "0033_ballotsopnhistory_ballotsopn"),
        ("sopn_parsing", "0005_awstextractparsedsopnimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awstextractparsedsopn",
            name="sopn",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="official_documents.ballotsopn",
            ),
        ),
        migrations.AlterField(
            model_name="camelotparsedsopn",
            name="sopn",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="official_documents.ballotsopn",
            ),
        ),
    ]
