# Generated by Django 4.2.10 on 2024-03-27 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sopn_parsing",
            "0006_rename_sopn_awstextractparsedsopn_official_document_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="awstextractparsedsopn",
            name="sopn",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="official_documents.ballotsopn",
            ),
        ),
        migrations.AddField(
            model_name="camelotparsedsopn",
            name="sopn",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="official_documents.ballotsopn",
            ),
        ),
    ]
