# Generated by Django 4.2.10 on 2024-03-27 10:04

from django.db import migrations
from django.db.models import OuterRef, Subquery


def move_parsed_sopns_to_ballot_sopn(apps, schema_editor):
    OfficialDocument = apps.get_model("official_documents", "OfficialDocument")
    CamelotParsedSOPN = apps.get_model("sopn_parsing", "CamelotParsedSOPN")
    AWSTextractParsedSOPN = apps.get_model(
        "sopn_parsing", "AWSTextractParsedSOPN"
    )

    latest_docs_subquery = (
        OfficialDocument.objects.filter(ballot=OuterRef("ballot_id"))
        .order_by("-created")
        .values("id")[:1]
    )

    latest_official_docs = OfficialDocument.objects.filter(
        id__in=Subquery(latest_docs_subquery)
    )

    for model_class in (CamelotParsedSOPN, AWSTextractParsedSOPN):
        qs = (
            model_class.objects.all()
            .select_related("official_document__ballot__sopn")
            .exclude(official_document__ballot__sopn=None)
            .filter(official_document__in=latest_official_docs)
        )
        for model in qs:
            if model.sopn:
                continue
            model.sopn = model.official_document.ballot.sopn
            model.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "sopn_parsing",
            "0007_awstextractparsedsopn_sopn_camelotparsedsopn_sopn",
        ),
    ]

    operations = [
        migrations.RunPython(
            code=move_parsed_sopns_to_ballot_sopn,
            reverse_code=migrations.RunPython.noop,
        )
    ]
