# Generated by Django 4.2.10 on 2024-03-27 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("official_documents", "0035_move_officialdocument_to_ballot_sopn"),
        ("sopn_parsing", "0008_move_to_ballot_sopn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awstextractparsedsopn",
            name="official_document",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="official_documents.officialdocument",
            ),
        ),
        migrations.AlterField(
            model_name="camelotparsedsopn",
            name="official_document",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="official_documents.officialdocument",
            ),
        ),
    ]
