# Generated by Django 3.2.10 on 2021-12-14 17:21

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RawPeople",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("data", models.JSONField()),
                ("source", models.CharField(max_length=512)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("bulk_add_form", "Bulk Add form"),
                            ("council_csv", "Council CSV"),
                            ("parsed_pdf", "Parsed from a PDF"),
                        ],
                        default="bulk_add_form",
                        max_length=255,
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
