# Generated by Django 3.2.10 on 2021-12-15 10:03

from django.db import migrations, models
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    replaces = [
        ("bulk_adding", "0001_add_trusted_to_bulk_add_group"),
        ("bulk_adding", "0002_rawpeople"),
        ("bulk_adding", "0003_rawpeople_source_type"),
        ("bulk_adding", "0004_move_to_jsonfield"),
        ("bulk_adding", "0005_source_max_length"),
        ("bulk_adding", "0006_auto_20210401_0811"),
        ("bulk_adding", "0007_alter_rawpeople_data"),
    ]

    initial = True

    dependencies = [("candidates", "0056_tmp_ids_to_ballot_id")]

    operations = [
        migrations.RunPython(
            code=django.db.migrations.operations.special.RunPython.noop,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.CreateModel(
            name="RawPeople",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("data", models.JSONField()),
                ("source", models.CharField(max_length=512)),
                (
                    "ballot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.postextraelection",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("bulk_add_form", "Bulk Add form"),
                            ("council_csv", "Council CSV"),
                            ("parsed_pdf", "Parsed from a PDF"),
                        ],
                        default="bulk_add_form",
                        max_length=255,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
