# Generated by Django 3.2.10 on 2021-12-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bulk_adding", "0001_initial"),
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawpeople",
            name="ballot",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="candidates.ballot",
            ),
        )
    ]
