# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-07 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bulk_adding", "0001_add_trusted_to_bulk_add_group"),
        ("candidates", "0056_tmp_ids_to_ballot_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawPeople",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("data", models.TextField()),
                ("source", models.CharField(max_length=255)),
                (
                    "ballot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="candidates.PostExtraElection",
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
