# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("bulk_adding", "0004_move_to_jsonfield")]

    operations = [
        migrations.AlterField(
            model_name="rawpeople",
            name="source",
            field=models.CharField(max_length=512),
        )
    ]
