# Generated by Django 2.2.16 on 2021-04-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("bulk_adding", "0005_source_max_length")]

    operations = [
        migrations.AlterField(
            model_name="rawpeople",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("bulk_add_form", "Bulk Add form"),
                    ("council_csv", "Council CSV"),
                    ("parsed_pdf", "Parsed from a PDF"),
                ],
                default="bulk_add_form",
                max_length=255,
            ),
        )
    ]
