# Generated by Django 4.2.8 on 2024-03-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_adding", "0008_rawpeople_aws_textract_parsed_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawpeople",
            name="aws_textract_parsed_data",
        ),
        migrations.AddField(
            model_name="rawpeople",
            name="textract_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="rawpeople",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
