# Generated by Django 5.2.9 on 2026-03-03 20:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_adding", "0010_delete_rawpeople"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawpeople",
            name="data",
        ),
    ]
