# Generated by Django 5.2.11 on 2026-03-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bulk_adding", "0011_remove_rawpeople_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawpeople",
            name="reconciled_data",
            field=models.JSONField(default=list),
        ),
    ]
