# Generated by Django 4.2.3 on 2023-10-17 13:25
import binascii
import os

from django.db import migrations
from django.utils.timezone import now


def add_auth_tokens(apps, schema_editor):
    User = apps.get_model("auth", "User")
    Token = apps.get_model("authtoken", "Token")

    for user in User.objects.filter(auth_token=None):
        token = Token(user=user, created=now())
        token.key = binascii.hexlify(os.urandom(20)).decode()
        token.save()


class Migration(migrations.Migration):
    dependencies = [("authtoken", "0003_tokenproxy")]

    operations = [
        (migrations.RunPython(add_auth_tokens, migrations.RunPython.noop))
    ]
