# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 21:15
from __future__ import unicode_literals

from django.db import migrations


def add_initial_profiles(apps, schema_editor):
    User = apps.get_model("auth", "User")
    WombleProfile = apps.get_model("wombles", "WombleProfile")
    for user in User.objects.all():
        try:
            WombleProfile.objects.create(user=user)
        except:
            pass


class Migration(migrations.Migration):

    dependencies = [("wombles", "0001_initial")]

    operations = [
        migrations.RunPython(add_initial_profiles, migrations.RunPython.noop)
    ]
