# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-07-11 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation_queue', '0021_remove_suggestedpostlock_post_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedimage',
            name='detection_metadata',
            field=models.TextField(blank=True),
        ),
    ]
