# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("moderation_queue", "0025_cleanup_old_lock_suggestions")]

    operations = [
        migrations.RenameField(
            model_name="suggestedpostlock",
            old_name="postextraelection",
            new_name="ballot",
        )
    ]
