# Generated by Django 2.2.4 on 2019-10-29 17:04

from django.db import migrations


def set_ints_to_zero(apps, schema_editor):
    QueuedImage = apps.get_model("moderation_queue", "QueuedImage")
    for field in ("crop_max_x", "crop_max_y", "crop_min_x", "crop_min_y"):
        filter_kwargs = {"{}__lt".format(field): 0}
        update_kwargs = {"{}".format(field): 0}
        QueuedImage.objects.filter(**filter_kwargs).update(**update_kwargs)


class Migration(migrations.Migration):

    dependencies = [("moderation_queue", "0026_rename_pee_to_ballot")]

    operations = [
        migrations.RunPython(set_ints_to_zero, migrations.RunPython.noop)
    ]
