# Generated by Django 2.2.4 on 2019-10-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderation_queue", "0027_positive_int_field_update_existing")
    ]

    operations = [
        migrations.AlterField(
            model_name="queuedimage",
            name="crop_max_x",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="queuedimage",
            name="crop_max_y",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="queuedimage",
            name="crop_min_x",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="queuedimage",
            name="crop_min_y",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
