# Generated by Django 2.2.16 on 2021-03-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("moderation_queue", "0030_add_very_trusted_user_group")]

    operations = [
        migrations.AddField(
            model_name="suggestedpostlock",
            name="ballot_hash",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        )
    ]
