# Generated by Django 3.2.4 on 2022-02-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("moderation_queue", "0031_suggestedpostlock_ballot_hash")]

    operations = [
        migrations.AlterField(
            model_name="queuedimage",
            name="why_allowed",
            field=models.CharField(
                choices=[
                    (
                        "public-domain",
                        "This photograph is free of any copyright restrictions",
                    ),
                    (
                        "copyright-assigned",
                        "I own copyright of this photo and I assign the copyright to Democracy Club in return for it being displayed on this site.",
                    ),
                    (
                        "profile-photo",
                        "This is the candidate's public profile photo from social media (e.g. Twitter, Facebook) or their official campaign page",
                    ),
                    ("other", "Other"),
                ],
                default="other",
                max_length=64,
            ),
        )
    ]
