# Generated by Django 4.1.7 on 2023-04-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderation_queue", "0032_update_copyright"),
    ]

    operations = [
        migrations.AddField(
            model_name="queuedimage",
            name="rotation_tried",
            field=models.BooleanField(default=False),
        ),
    ]
