# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-13 13:56

from django.conf import settings
from django.db import migrations


def create_user(apps, schema_editor):
    User = apps.get_model("auth", "User")
    User.objects.get_or_create(username=settings.TWITTER_BOT_USERNAME)


class Migration(migrations.Migration):
    dependencies = []

    operations = [migrations.RunPython(create_user, migrations.RunPython.noop)]
