version: '3'
volumes:
  psql-data:
services:
  psql:
    image: public.ecr.aws/docker/library/postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - psql-data:/var/lib/postgresql/data
    ports:
      - 5555:5432
