"""
NOTE: This file is needed to stop Django complaining, but
it doesn't actually do anything at all.

"""

# Generated by Django 4.1.7 on 2023-05-08 15:25

import data_exports.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("popolo", "0048_othername_needs_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterializedMemberships",
            fields=[],
            options={
                "db_table": "materialized_memberships",
                "managed": False,
            },
            bases=(data_exports.models.MaterializedModelMixin, models.Model),
        ),
    ]
