from candidates.views.agreement import *
from candidates.views.api import *
from candidates.views.areas import *
from candidates.views.candidacies import *
from candidates.views.constituencies import *
from candidates.views.help import *
from candidates.views.parties import *
from candidates.views.people import *
from candidates.views.posts import *
from candidates.views.search import *
from candidates.views.users import *
from candidates.views.other_names import *
