from candidates.views.agreement import *  # noqa
from candidates.views.areas import *  # noqa
from candidates.views.candidacies import *  # noqa
from candidates.views.constituencies import *  # noqa
from candidates.views.help import *  # noqa
from candidates.views.other_names import *  # noqa
from candidates.views.people import *  # noqa
from candidates.views.posts import *  # noqa
from candidates.views.search import *  # noqa
from candidates.views.users import *  # noqa
