# Generated by Django 3.2.10 on 2021-12-14 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Ballot",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, db_index=True, verbose_name="modified"
                    ),
                ),
                (
                    "ee_modified",
                    models.DateTimeField(
                        blank=True,
                        help_text="Stores the modified timestamp from EE",
                        null=True,
                    ),
                ),
                (
                    "ballot_paper_id",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                ("candidates_locked", models.BooleanField(default=False)),
                (
                    "winner_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("cancelled", models.BooleanField(default=False)),
                ("voting_system", models.CharField(blank=True, max_length=255)),
                ("tags", models.JSONField(blank=True, default=dict)),
            ],
            options={"get_latest_by": "modified", "abstract": False},
        ),
        migrations.CreateModel(
            name="LoggedAction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "person_pk",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="This is stored to help us identify the related person an action was for after the Person has been deleted",
                        null=True,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("entered-results-data", "Entered results"),
                            ("set-candidate-elected", "Set Candidate elected"),
                            (
                                "set-candidate-not-elected",
                                "Set Candidate not elected",
                            ),
                            ("person-lock", "Person locked"),
                            ("person-update", "Person updated"),
                            ("person-create", "Person created"),
                            ("person-delete", "Person deleted"),
                            (
                                "person-other-name-create",
                                "Person Other name created",
                            ),
                            (
                                "person-other-name-delete",
                                "Person Other name deleted",
                            ),
                            (
                                "person-other-name-update",
                                "Person Other name updated",
                            ),
                            ("person-revert", "Person reverted"),
                            ("constituency-lock", "Constituency locked"),
                            ("constituency-unlock", "Constituency unlocked"),
                            ("candidacy-create", "Candidacy created"),
                            ("candidacy-delete", "Candidacy deleted"),
                            ("photo-approve", "Photo approved"),
                            ("photo-upload", "Photo uploaded"),
                            ("photo-reject", "Photo rejected"),
                            ("photo-ignore", "Photo ignored"),
                            ("suggest-ballot-lock", "Suggested ballot lock"),
                            ("person-merge", "Person merged"),
                            (
                                "record-council-result",
                                "Recorded council result",
                            ),
                            (
                                "confirm-council-result",
                                "Confirmed council result ",
                            ),
                            ("sopn-upload", "SOPN uploaded"),
                            (
                                "record-council-control",
                                "Recorded council control",
                            ),
                            (
                                "confirm-council-control",
                                "Confirmed council control",
                            ),
                            ("retract-winner", "Retracted winner"),
                            ("duplicate-suggest", "Duplicate suggested"),
                            (
                                "change-edit-limitations",
                                "Changed edit limitations",
                            ),
                            (
                                "suspended-twitter-account",
                                "Suspended Twitter account",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                ("popit_person_new_version", models.CharField(max_length=32)),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "ip_address",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("source", models.TextField()),
                (
                    "flagged_type",
                    models.CharField(
                        blank=True,
                        help_text="If NOT NULL, a type of flag that marks this edit as needing review by a human",
                        max_length=100,
                    ),
                ),
                (
                    "flagged_reason",
                    models.CharField(
                        blank=True,
                        help_text="An explaination of the reason for flagging this edit",
                        max_length=255,
                    ),
                ),
                (
                    "edit_type",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("BOT", "Bot"),
                            ("BULK_ADD", "Bulk Add"),
                        ],
                        default="USER",
                        max_length=20,
                    ),
                ),
                ("approved", models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PartySet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=256, unique=True)),
                ("name", models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name="PersonRedirect",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_person_id", models.IntegerField()),
                ("new_person_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserTermsAgreement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_to_dc", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_agreement",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
