# Generated by Django 3.2.10 on 2021-12-14 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("popolo", "0001_initial"),
        ("people", "0001_initial"),
        ("candidates", "0001_initial"),
        ("elections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="partyset",
            name="parties",
            field=models.ManyToManyField(
                related_name="party_sets", to="popolo.Organization"
            ),
        ),
        migrations.AddField(
            model_name="loggedaction",
            name="ballot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="candidates.ballot",
            ),
        ),
        migrations.AddField(
            model_name="loggedaction",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.person",
            ),
        ),
        migrations.AddField(
            model_name="loggedaction",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="popolo.post",
            ),
        ),
        migrations.AddField(
            model_name="loggedaction",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ballot",
            name="election",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="elections.election",
            ),
        ),
        migrations.AddField(
            model_name="ballot",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="popolo.post"
            ),
        ),
        migrations.AddField(
            model_name="ballot",
            name="replaces",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="replaced_by",
                to="candidates.ballot",
            ),
        ),
    ]
