# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-23 14:00


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0040_membershipextra_post_election'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipextra',
            name='post_election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidates.PostExtraElection'),
        ),
    ]
