# Generated by Django 1.9.13 on 2018-05-15 15:55


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("candidates", "0043_remove_simple_popolo_field")]

    operations = [
        migrations.RemoveField(model_name="membershipextra", name="election")
    ]
