# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-14 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popolo', '0009_move_extra_person_data_to_base'),
        ('candidates', '0045_delete_membership_extra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonExtra',
        ),
    ]
