# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-26 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("candidates", "0050_delete_imageextra")]

    operations = [
        migrations.RemoveField(model_name="areaextra", name="base"),
        migrations.RemoveField(model_name="areaextra", name="type"),
        migrations.DeleteModel(name="AreaExtra"),
    ]
