# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-24 07:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0004_move_person_data"),
        ("candidates", "0052_python_3_changes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loggedaction",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="people.Person",
            ),
        ),
        migrations.AlterField(
            model_name="personextrafieldvalue",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_field_values",
                to="people.Person",
            ),
        ),
    ]
