# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-25 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("candidates", "0053_move_person_fk_to_people_app")]

    operations = [
        migrations.AddField(
            model_name="postextraelection",
            name="cancelled",
            field=models.BooleanField(default=False),
        )
    ]
