# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-14 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0054_postextraelection_cancelled"),
        ("people", "0009_copy_popolo_fields_to_person_identifiers"),
    ]

    operations = [migrations.DeleteModel(name="ComplexPopoloField")]
