# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 14:03
from __future__ import unicode_literals

from django.db import migrations


def move_tmp_ids_to_actual_ids(apps, schema_editor):
    PostExtraElection = apps.get_model("candidates", "PostExtraElection")

    pees_with_tmp_ids = PostExtraElection.objects.filter(
        ballot_paper_id__startswith="tmp_"
    )
    if not pees_with_tmp_ids.exists():
        # Return quickly if no tmp ids exist, to save iterating over the file
        # needlessly
        return

    data_file = open(
        "ynr/apps/candidates/migrations/0056_tmp_ids_to_ballot_id.csv"
    )
    for line in data_file:
        tmp_id, new_id = line.split(",")
        PostExtraElection.objects.filter(ballot_paper_id=tmp_id).update(
            ballot_paper_id=new_id.strip()
        )


class Migration(migrations.Migration):

    dependencies = [("candidates", "0055_delete_complexpopolofield")]

    operations = [
        migrations.RunPython(
            move_tmp_ids_to_actual_ids, migrations.RunPython.noop
        )
    ]
