# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0056_tmp_ids_to_ballot_id"),
        ("people", "0014_remove_person_email"),
        ("uk", "0005_add_favourite_biscuits"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="personextrafieldvalue", unique_together=set([])
        ),
        migrations.RemoveField(
            model_name="personextrafieldvalue", name="field"
        ),
        migrations.RemoveField(
            model_name="personextrafieldvalue", name="person"
        ),
        migrations.DeleteModel(name="ExtraField"),
        migrations.DeleteModel(name="PersonExtraFieldValue"),
    ]
