# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0057_remove_extra_field"),
        ("official_documents", "0024_add_relevant_pages"),
    ]

    operations = [
        migrations.RenameModel(old_name="PostExtraElection", new_name="Ballot")
    ]
