# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-16 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("candidates", "0058_pee_to_ballot")]

    operations = [
        migrations.RenameField(
            model_name="loggedaction",
            old_name="post_election",
            new_name="ballot",
        )
    ]
