# Generated by Django 2.2.4 on 2019-09-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("candidates", "0059_rename_logged_action_fk_to_ballot")]

    operations = [
        migrations.AddField(
            model_name="loggedaction",
            name="flagged_reason",
            field=models.CharField(
                blank=True,
                help_text="An explaination of the reason for flagging this edit",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="loggedaction",
            name="flagged_type",
            field=models.CharField(
                blank=True,
                help_text="If NOT NULL, a type of flag that marks this edit as needing review by a human",
                max_length=100,
            ),
        ),
    ]
