# Generated by Django 2.2.4 on 2019-10-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("candidates", "0060_add_flagged_type")]

    operations = [
        migrations.AlterField(
            model_name="ballot",
            name="winner_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        )
    ]
