# Generated by Django 2.2.4 on 2019-11-13 22:27

import candidates.models.db
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("candidates", "0061_positive_int_field")]

    operations = [
        migrations.AddField(
            model_name="loggedaction",
            name="edit_type",
            field=models.CharField(
                choices=[
                    ("USER", "User"),
                    ("BOT", "Bot"),
                    ("BULK_ADD", "Bulk Add"),
                ],
                default=candidates.models.db.EditType("User").name,
                max_length=20,
            ),
        )
    ]
