# Generated by Django 2.2.16 on 2021-03-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("candidates", "0065_ballot_replaces")]

    operations = [
        migrations.AlterUniqueTogether(name="ballot", unique_together=set())
    ]
