# Generated by Django 2.2.18 on 2021-04-01 14:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("candidates", "0066_drop_unique_on_election_post")]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="tags",
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        )
    ]
