# Generated by Django 2.2.18 on 2021-04-07 09:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("candidates", "0067_ballot_tags")]

    operations = [
        migrations.AlterField(
            model_name="ballot",
            name="tags",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=dict
            ),
        )
    ]
