# Generated by Django 2.2.18 on 2021-05-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("candidates", "0068_add_blank_to_tags")]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="voting_system",
            field=models.CharField(blank=True, max_length=255),
        )
    ]
