# Generated by Django 3.2.4 on 2021-09-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("candidates", "0072_alter_ballot_options")]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="ee_modified",
            field=models.DateTimeField(
                blank=True,
                help_text="Stores the modified timestamp from EE",
                null=True,
            ),
        )
    ]
