# Generated by Django 3.2.4 on 2021-09-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("candidates", "0073_ballot_ee_modified")]

    operations = [
        migrations.AlterField(
            model_name="ballot",
            name="tags",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="loggedaction",
            name="approved",
            field=models.JSONField(null=True),
        ),
    ]
