# Generated by Django 3.2.4 on 2021-10-06 09:27

from django.db import migrations


def clean_up_action_types(apps, schema_editor):
    LoggedAction = apps.get_model("candidates", "LoggedAction")
    action_types = LoggedAction.objects.filter(
        action_type=["constituency--lock"]
    )
    action_types.update(action_type="constituency-lock")


class Migration(migrations.Migration):
    dependencies = [("candidates", "0073_alter_loggedaction_action_type")]

    operations = [
        migrations.RunPython(clean_up_action_types, migrations.RunPython.noop)
    ]
