# Generated by Django 3.2.4 on 2021-09-29 16:10

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("candidates", "0075_use_jsonfield_from_django")]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="ee_modified",
            field=models.DateTimeField(
                blank=True,
                help_text="Stores the modified timestamp from EE",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ballot",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, db_index=True, verbose_name="modified"
            ),
        ),
    ]
