# Generated by Django 3.2.4 on 2021-10-25 16:58

from django.db import migrations
from django.db.models import F


def forwards(apps, schema_editor):
    LoggedAction = apps.get_model("candidates", "LoggedAction")
    LoggedAction.objects.filter(person__isnull=False).update(
        person_pk=F("person__pk")
    )


class Migration(migrations.Migration):
    dependencies = [("candidates", "0077_loggedaction_person_pk")]

    operations = [
        migrations.RunPython(
            code=forwards, reverse_code=migrations.RunPython.noop
        )
    ]
