# Generated by Django 3.2.4 on 2021-10-25 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0033_auto_20210928_1007"),
        ("candidates", "0078_populate_person_pk_on_loggedaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loggedaction",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="people.person",
            ),
        )
    ]
