# Generated by Django 3.2.12 on 2022-04-28 15:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("candidates", "0082_alter_ballot_winner_count")]

    operations = [
        migrations.AddField(
            model_name="loggedaction",
            name="version_fields",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200),
                blank=True,
                help_text="The fields that have changed",
                null=True,
                size=None,
            ),
        )
    ]
