# Generated by Django 4.1.7 on 2023-04-20 20:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0083_loggedaction_version_fields"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserTermsAgreement",
        ),
    ]
