# Generated by Django 4.2.8 on 2024-02-26 19:53

import django.utils.timezone
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0084_delete_usertermsagreement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="personredirect",
            options={"get_latest_by": "modified"},
        ),
        migrations.AddField(
            model_name="personredirect",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personredirect",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
