# Generated by Django 4.2.16 on 2025-09-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0088_alter_ballot_voting_system_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="by_election_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DEATH", "The elected member died"),
                    ("RESIGNATION", "The elected member resigned"),
                    (
                        "ELECTORAL_COURT",
                        "The election of the elected member was declared void by an election court",
                    ),
                    (
                        "FAILURE_TO_ACCEPT",
                        "The previous election winner did not sign a declaration of acceptance",
                    ),
                    (
                        "FAILURE_TO_ATTEND_MEETINGS",
                        "The elected member failed to attend meetings for six months",
                    ),
                    ("DISQUALIFICATION", "The elected member was disqualified"),
                    (
                        "LOSING_QUALIFICATION",
                        "The elected member no longer qualified as a registered elector",
                    ),
                    (
                        "RECALL_PETITION",
                        "The elected member was recalled by a successful recall petition",
                    ),
                    ("OTHER", "Other"),
                    ("UNKNOWN", "Unknown"),
                    ("", "Neither a by-election nor a ballot"),
                ],
                default="",
                help_text='\n    Reasons why a by-election may be triggered.\n\n    Not all of these can be applied to all election types.\n\n    e.g. a recall petition is only used in Westminster, and failure to attend meetings\n    applies to local government.\n\n    An empty string represents ballots that are not applicable, e.g because they\'re not by-elections.\n\n    The choices here are in part based on:\n        UK Electoral Commission guidance on casual vacancies:\n        <a href="https://www.electoralcommission.org.uk/guidance-returning-officers-administering-local-government-elections-england/casual-vacancies-and-elections/how-casual-vacancies-occur">https://www.electoralcommission.org.uk/guidance-returning-officers-administering-local-government-elections-england/casual-vacancies-and-elections/how-casual-vacancies-occur</a>\n    ',
                max_length=30,
            ),
        ),
    ]
