# Generated by Django 5.2.13 on 2026-06-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0090_alter_loggedaction_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballot",
            name="voting_system",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AMS", "Additional Member System (Party List)"),
                    ("FPTP", "First-past-the-post"),
                    ("sv", "Supplementary Vote"),
                    ("STV", "Single Transferable Vote"),
                    ("PR-CL", "Closed List"),
                ],
                max_length=255,
            ),
        ),
    ]
