# Generated by Django 5.2.15 on 2026-07-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("candidates", "0094_alter_ballot_by_election_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="close_of_nominations",
            field=models.DateField(
                blank=True, help_text="Close of Nominations", null=True
            ),
        ),
        migrations.AddField(
            model_name="ballot",
            name="sopn_publish_deadline",
            field=models.DateField(
                blank=True,
                help_text="Deadline to publish SOPN document",
                null=True,
            ),
        ),
    ]
